# Generated by Django 5.2.11 on 2026-02-09 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='businesssettings',
            name='card_payment_url',
            field=models.URLField(blank=True, help_text='URL for online card payment (e.g. SumUp link)'),
        ),
        migrations.AddField(
            model_name='businesssettings',
            name='vat_registration',
            field=models.CharField(blank=True, default='N/A', help_text='VAT registration number, or N/A if not registered', max_length=50),
        ),
        migrations.AddField(
            model_name='businesssettings',
            name='website',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='owner',
            name='account_code',
            field=models.CharField(blank=True, help_text='Account code for accounting systems (e.g. Xero)', max_length=20),
        ),
    ]
