# Generated by Django 5.2.11 on 2026-02-11 10:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_add_account_code_website_vat'),
    ]

    operations = [
        migrations.AddField(
            model_name='horse',
            name='dam',
            field=models.ForeignKey(blank=True, help_text='Dam (mother) if she is in the system', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='offspring_as_dam', to='core.horse'),
        ),
        migrations.AddField(
            model_name='horse',
            name='date_of_birth',
            field=models.DateField(blank=True, help_text='Date of birth', null=True),
        ),
        migrations.AddField(
            model_name='horse',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='horses/'),
        ),
        migrations.AddField(
            model_name='horse',
            name='sire_name',
            field=models.CharField(blank=True, help_text='Stallion name', max_length=200),
        ),
        migrations.AlterField(
            model_name='horse',
            name='age',
            field=models.PositiveIntegerField(blank=True, help_text='Age in years (used if DOB unknown)', null=True),
        ),
        migrations.AlterField(
            model_name='horse',
            name='breeding',
            field=models.TextField(blank=True, help_text='Sire/dam information (free text)'),
        ),
    ]
