# Generated by Django 5.2.11 on 2026-02-23 11:25

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_horse_is_active_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoicelineitem',
            name='share_percentage',
            field=models.DecimalField(decimal_places=2, default=Decimal('100.00'), help_text='Ownership share % at time of invoicing', max_digits=5),
        ),
        migrations.CreateModel(
            name='OwnershipShare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('share_percentage', models.DecimalField(decimal_places=2, help_text='Ownership percentage (e.g. 50.00 for 50%)', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.01')), django.core.validators.MaxValueValidator(Decimal('100.00'))])),
                ('is_primary_contact', models.BooleanField(default=False, help_text='Primary contact for this horse')),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('horse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ownership_shares', to='core.horse')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ownership_shares', to='core.owner')),
            ],
            options={
                'ordering': ['-share_percentage'],
                'indexes': [models.Index(fields=['horse', 'owner'], name='ownership_horse_owner')],
                'unique_together': {('horse', 'owner')},
            },
        ),
    ]
