# Generated by Django 5.2.11 on 2026-02-24 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_populate_ownership_shares'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='placement',
            index=models.Index(fields=['horse', 'end_date'], name='placement_horse_enddate'),
        ),
        migrations.AddIndex(
            model_name='placement',
            index=models.Index(fields=['horse', 'location', 'end_date'], name='placement_horse_loc_end'),
        ),
        migrations.AddIndex(
            model_name='placement',
            index=models.Index(fields=['horse', 'owner', 'end_date'], name='placement_horse_owner_end'),
        ),
    ]
