# Generated by Django 5.2.11 on 2026-02-09 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExtraCharge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('charge_type', models.CharField(choices=[('vet', 'Veterinary'), ('farrier', 'Farrier'), ('feed', 'Feed/Hay'), ('medication', 'Medication'), ('transport', 'Transport'), ('equipment', 'Equipment'), ('dentist', 'Dentist'), ('physio', 'Physiotherapy'), ('other', 'Other')], default='other', max_length=20)),
                ('date', models.DateField()),
                ('description', models.CharField(max_length=500)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('invoiced', models.BooleanField(default=False)),
                ('receipt_image', models.ImageField(blank=True, null=True, upload_to='receipts/%Y/%m/')),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='ServiceProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('provider_type', models.CharField(choices=[('vet', 'Veterinarian'), ('farrier', 'Farrier'), ('dentist', 'Equine Dentist'), ('physio', 'Physiotherapist'), ('saddler', 'Saddler'), ('other', 'Other')], default='other', max_length=20)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('address', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['provider_type', 'name'],
            },
        ),
    ]
