# Generated by Django 5.2.11 on 2026-02-09 11:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('billing', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='extracharge',
            name='horse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extra_charges', to='core.horse'),
        ),
        migrations.AddField(
            model_name='extracharge',
            name='invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='extra_charges', to='core.invoice'),
        ),
        migrations.AddField(
            model_name='extracharge',
            name='owner',
            field=models.ForeignKey(help_text='Who pays for this charge', on_delete=django.db.models.deletion.PROTECT, related_name='extra_charges', to='core.owner'),
        ),
        migrations.AddField(
            model_name='extracharge',
            name='service_provider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='charges', to='billing.serviceprovider'),
        ),
    ]
