# Generated by Django 5.2.11 on 2026-02-24 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0004_add_split_by_ownership'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extracharge',
            name='charge_type',
            field=models.CharField(choices=[('vet', 'Veterinary'), ('farrier', 'Farrier'), ('vaccination', 'Vaccination'), ('feed', 'Feed/Hay'), ('medication', 'Medication'), ('transport', 'Transport'), ('equipment', 'Equipment'), ('dentist', 'Dentist'), ('physio', 'Physiotherapy'), ('other', 'Other')], default='other', max_length=20),
        ),
    ]
