# Generated by Django 5.2.11 on 2026-02-09 11:02

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('billing', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VaccinationType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('interval_months', models.PositiveIntegerField(default=12, help_text='Months between vaccinations')),
                ('reminder_days_before', models.PositiveIntegerField(default=30, help_text='Days before due date to send reminder')),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='FarrierVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('work_done', models.CharField(choices=[('trim', 'Trim Only'), ('front_shoes', 'Front Shoes'), ('full_set', 'Full Set'), ('remedial', 'Remedial Work'), ('remove', 'Shoe Removal')], default='trim', max_length=20)),
                ('next_due_date', models.DateField(blank=True, null=True)),
                ('cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('extra_charge', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='farrier_visit', to='billing.extracharge')),
                ('horse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='farrier_visits', to='core.horse')),
                ('service_provider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='farrier_visits', to='billing.serviceprovider')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Vaccination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_given', models.DateField()),
                ('next_due_date', models.DateField()),
                ('vet_name', models.CharField(blank=True, max_length=200)),
                ('batch_number', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('reminder_sent', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('horse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vaccinations', to='core.horse')),
                ('vaccination_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vaccinations', to='health.vaccinationtype')),
            ],
            options={
                'ordering': ['-date_given'],
            },
        ),
    ]
