# Generated by Django 5.2.11 on 2026-02-11 10:47

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_alter_extracharge_amount'),
        ('core', '0003_horse_dam_horse_date_of_birth_horse_photo_and_more'),
        ('health', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BreedingRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stallion_name', models.CharField(max_length=200)),
                ('date_covered', models.DateField()),
                ('date_scanned_14_days', models.DateField(blank=True, help_text='In-foal scan', null=True)),
                ('date_scanned_heartbeat', models.DateField(blank=True, null=True)),
                ('date_foal_due', models.DateField(blank=True, null=True)),
                ('foal_dob', models.DateField(blank=True, null=True)),
                ('foal_sex', models.CharField(blank=True, choices=[('colt', 'Colt'), ('filly', 'Filly')], max_length=20)),
                ('foal_colour', models.CharField(blank=True, choices=[('bay', 'Bay'), ('chestnut', 'Chestnut'), ('grey', 'Grey'), ('black', 'Black'), ('brown', 'Brown'), ('palomino', 'Palomino'), ('skewbald', 'Skewbald'), ('piebald', 'Piebald'), ('roan', 'Roan'), ('dun', 'Dun'), ('cream', 'Cream'), ('other', 'Other')], max_length=20)),
                ('foal_microchip', models.CharField(blank=True, max_length=100)),
                ('foaling_notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('covered', 'Covered'), ('confirmed', 'Confirmed In-Foal'), ('born', 'Born'), ('lost', 'Lost'), ('barren', 'Barren')], default='covered', max_length=20)),
                ('ehv_reminders_sent', models.CharField(blank=True, help_text='Comma-separated list of EHV reminder months already sent (e.g. 5,7)', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('foal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='birth_record', to='core.horse')),
                ('mare', models.ForeignKey(limit_choices_to={'sex': 'mare'}, on_delete=django.db.models.deletion.CASCADE, related_name='breeding_records', to='core.horse')),
            ],
            options={
                'ordering': ['-date_covered'],
            },
        ),
        migrations.CreateModel(
            name='MedicalCondition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g. Laminitis, Sweet Itch', max_length=200)),
                ('diagnosed_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('resolved', 'Resolved'), ('monitoring', 'Monitoring')], default='active', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('horse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medical_conditions', to='core.horse')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VetVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('reason', models.CharField(max_length=500)),
                ('diagnosis', models.TextField(blank=True)),
                ('treatment', models.TextField(blank=True)),
                ('follow_up_date', models.DateField(blank=True, null=True)),
                ('cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('extra_charge', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vet_visit', to='billing.extracharge')),
                ('horse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vet_visits', to='core.horse')),
                ('vet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vet_visits', to='billing.serviceprovider')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='WormEggCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('count', models.PositiveIntegerField(help_text='Eggs per gram (EPG)')),
                ('lab_name', models.CharField(blank=True, max_length=200)),
                ('sample_type', models.CharField(choices=[('fec', 'Faecal Egg Count (FEC)'), ('saliva', 'Saliva Test'), ('other', 'Other')], default='fec', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('horse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='worm_egg_counts', to='core.horse')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='WormingTreatment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('product_name', models.CharField(help_text='Brand name of wormer', max_length=200)),
                ('active_ingredient', models.CharField(blank=True, max_length=200)),
                ('dose', models.CharField(blank=True, max_length=100)),
                ('administered_by', models.CharField(blank=True, max_length=200)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('horse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='worming_treatments', to='core.horse')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
