# Generated by Django 5.2.11 on 2026-02-24 16:10

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0002_breedingrecord_medicalcondition_vetvisit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='farriervisit',
            name='reminder_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vaccinationtype',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='vaccinationtype',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='vaccination',
            name='next_due_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
